# Generated by Django 5.0.3 on 2024-11-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_connlog_filelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='rustdesdevice',
            name='ip',
            field=models.CharField(default='', max_length=16, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='rustdeskpeer',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='IP Address'),
        ),
    ]
