# Generated by Django 5.2.3 on 2025-06-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rustdesdevice_ip_rustdeskpeer_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_recovery_codes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_secret_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
